# Generated by Django 4.0.1 on 2022-01-26 21:49

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htsolutions.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htsolutions.family')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('currency', models.CharField(choices=[('€', 'EUROS (€)'), ('$', 'US DOLARS ($)'), ('£', 'LIBRAS (£)')], default='€', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='not_found.jpg', upload_to='')),
                ('ean', models.PositiveIntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(1, message=None), django.core.validators.MinValueValidator(1, message=None), django.core.validators.MinLengthValidator(13, message=None)])),
                ('createdDate', models.DateField(default=datetime.date.today)),
                ('expectedAvailabilityDate', models.DateField(blank=True, null=True)),
                ('expectedDeliveryDate', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0, max_length=3)),
                ('stockStatus', models.CharField(blank=True, choices=[('0', 'Sem Stock'), ('1', 'Em Stock'), ('2', 'Por Encomenda')], default='0', help_text='Stock do produto', max_length=1)),
                ('attribute', models.ManyToManyField(to='htsolutions.Attribute')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htsolutions.brand')),
                ('subFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htsolutions.subfamily')),
            ],
        ),
    ]
