# Generated by Django 4.0.1 on 2022-01-26 21:59

import django.core.validators
from django.db import migrations, models
import htsolutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('htsolutions', '0003_alter_product_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.PositiveIntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
    ]
