# Generated by Django 4.0.1 on 2022-01-26 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htsolutions', '0010_alter_product_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(default='0000000000001', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('[1-9]\\d*'), django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
