# Generated by Django 4.0.1 on 2022-01-26 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htsolutions', '0011_alter_product_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stockStatus',
            field=models.CharField(choices=[('0', 'Sem Stock'), ('1', 'Em Stock'), ('2', 'Por Encomenda')], default='0', help_text='Stock do produto', max_length=1, validators=[django.core.validators.RegexValidator('[1-3]'), django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1)]),
        ),
    ]
